### PR TITLE
We need to define that binding to 443 requires ssl

### PR DESCRIPTION
**Pull request by armiller**
I don't know how this go through with all of our testing.

### CODE REVIEW

**Comment by jordane** [comment]
Can you squash these two commits please?

**Comment by armiller** [comment]
@jordane done

**Comment by jordane** [comment]
+1

**Comment by ramereth** [comment]
@armiller your tests need to be updated that match the bind line in ``haproxy.cfg``.

**Comment by armiller** [comment]
@osuosl-cookbooks/chefs I updated the tests and they pass tk. Should I push the updated test kitchen config that works for now with test-kitchen 1.4?

**Comment by ramereth** [comment]
:+1:

**Pull request merged**
